stages:
  - deploy
publish:
  image: 'node:10.10.0-jessie'
  stage: deploy
  cache:
    key: eff-table
    paths:
      - node_modules/
  script:
    - 'npm config set registry http://192.168.88.9:8081/repository/npmall/'
    - 'npm config set disturl https://npm.taobao.org/dist –global'
    - 'export SASS_BINARY_SITE=https://npm.taobao.org/mirrors/node-sass'
    - npm install --loglevel verbose
    - npm run build
    - 'echo export default $CI_PIPELINE_ID > version.js'
    - npm publish --registry=http://192.168.88.9:8081/repository/npmlocal/
  tags:
    - docker 
